### PR TITLE
Travis deprecation warnings fix

### PR DESCRIPTION
**Pull request by mgiagante**
The following errors were preventing Travis CI build from passing:
```
DEPRECATION WARNING: The configuration option `config.serve_static_assets` has been renamed to `config.serve_static_files` to clarify its role (it merely enables serving everything in the `public` folder and is unrelated to the asset pipeline). The `serve_static_assets` alias will be removed in Rails 5.0. Please migrate your configuration files accordingly. (called from block in <top (required)> at /home/travis/build/elorest/petergate/dummy/config/environments/test.rb:16)
```
```
DEPRECATION WARNING: [Devise] including `Devise::TestHelpers` is deprecated and will be removed from Devise.
For controller tests, please include `Devise::Test::ControllerHelpers` instead.
 (called from include at /home/travis/build/elorest/petergate/dummy/test/test_helper.rb:22)
```
```
DEPRECATION WARNING: You did not specify a value for the configuration option `active_support.test_order`. In Rails 5, the default value of this option will change from `:sorted` to `:random`.
To disable this warning and keep the current behavior, you can add the following line to your `config/environments/test.rb`:
  Rails.application.configure do
    config.active_support.test_order = :sorted
  end
Alternatively, you can opt into the future behavior by setting this option to `:random`. (called from test_order at /home/travis/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/test_case.rb:42)
```

I fixed them by following the recommendations they included, and keeping the test execution order as :sorted (the value it originally had by default and changed as of Rails 5).

### CODE REVIEW

**Comment by mgiagante** [comment]
@elorest This fixes some deprecation warnings. I noticed the tests are running on Rails 4.2. I wonder if the BlogsController::Multiple test fails because it uses #assign for getting the fixtures.
I'll be taking a look shortly.

**Comment by mgiagante** [comment]
@elorest I'm still getting this error when trying to merge:
```
BlogsController::Multiple: Make sure guests can't see what they shouldn't.
  test_0001_guest can see index                                   PASS (0.35s)
/home/travis/.rvm/gems/ruby-2.3.1/gems/minitest-reporters-1.3.1/lib/minitest/reporters/base_reporter.rb:114:in `const_get': wrong constant name Multiple: Make sure guests can't see what they shouldn't. (NameError)
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/minitest-reporters-1.3.1/lib/minitest/reporters/base_reporter.rb:114:in `block in load_constant'
```

Not idea why this happens right after the first test. Tests seem to be correctly defined. All I can think of is the #assigns method, since it got [deprecated] (https://apidock.com/rails/ActionController/TestProcess/assigns#441-used-for-testing-) , but as the tests run in Rails 4.2... I don't think this is the problem.

Is there a way to run those tests locally to use byebug? I'm not familiar with Travis but if there's anything I can do to help, just let me know.

**Comment by elorest** [comment]
@mgiagante Thanks for this. If you had any time to upgrade the tests to run in rails 5.x that would be greatly appreciated. I'm currently using it in a pretty large Rails 5.1 project and don't have any issues but the test suite could definitely be updated. Hacktoberfest is coming up: https://hacktoberfest.digitalocean.com/

**Comment by elorest** [comment]
I'll try to find some time in the next month to work on this as well although I suppose most of my open source time will be working on https://amberframework.org still.

**Comment by elorest** [comment]
@mgiagante 
> Is there a way to run those tests locally to use byebug? I'm not familiar with Travis but if there's anything I can do to help, just let me know.

You can run the tests locally:

`bundle install && cd dummy && rake db:create && rake db:migrate`
`bundle exec rake test`

**Pull request merged**
